export class Alquiler{
    constructor(
        public _id: String,
        public numero: String,
        public tipo: String,
        public cancha: String,
        public tarifa: String,
        public cliente: String,
        public fechaAlquiler: Date,
        public estado: Boolean,
        public subtotal: String,
        public fecha: Date,
        public una: {type:Boolean,default:true},
        public dos: {type:Boolean,default:true},
        public tres: {type:Boolean,default:true},
        public cuatro: {type:Boolean,default:true},
        public cinco: {type:Boolean,default:true},
        public seis: {type:Boolean,default:true},
        public siete: {type:Boolean,default:true},
        public ocho: {type:Boolean,default:true},
        public nueve: {type:Boolean,default:true},
        public diez: {type:Boolean,default:true},
        public oncee: {type:Boolean,default:true},
        public doce: {type:Boolean,default:true},
        public trece: {type:Boolean,default:true},
        public catorce: {type:Boolean,default:true},
        public quince: {type:Boolean,default:true},
        public diezyseis: {type:Boolean,default:true},
        public diezysiete: {type:Boolean,default:true},
        public diezyocho: {type:Boolean,default:true},
        public diezynueve: {type:Boolean,default:true},
        public veinte: {type:Boolean,default:true},
        public veinteyuno: {type:Boolean,default:true},
        public veinteydos: {type:Boolean,default:true},
        public veinteytres: {type:Boolean,default:true},
        public cero: {type:Boolean,default:true}
        
    ){}
   
}
