export class Tarifa{
    constructor(
        public _id:string,
        public nombre: String,
        public estado:String,
        public valor:String,
        public lunes: Boolean,
        public martes: Boolean,
        public miercoles: Boolean,
        public jueves: Boolean,
        public viernes: Boolean,
        public sabado: Boolean,
        public domingo: Boolean,
        public una: Boolean,
        public dos: Boolean,
        public tes: Boolean,
        public cuatro: Boolean,
        public cinco: Boolean,
        public seis: Boolean,
        public siete: Boolean,
        public ocho: Boolean,
        public nueve: Boolean,
        public diez: Boolean,
        public once: Boolean,
        public doce: Boolean,
        public trece: Boolean,
        public catorce: Boolean,
        public quince: Boolean,
        public diezyseis: Boolean,
        public diezysiete: Boolean,
        public diezyocho: Boolean,
        public diezynueve: Boolean,
        public veinte: Boolean,
        public veinteyuno: Boolean,
        public veinteydos: Boolean,
        public veinteytres: Boolean,
        public cero: Boolean,
    ){}
   
}